[package]
name = "nomos-warp"
description = "Warp: dependency and execution-graph engine (Action DAG)."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
publish.workspace = true

[lints]
workspace = true

[dependencies]
nomos-core.workspace = true

[dev-dependencies]
proptest.workspace = true
